[package]
name = "crypto-tracker"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
time = { version = "0.3", features = ["macros", "serde-human-readable"] }
cfg-if = "1"

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1