# wrangler.toml

name = "crypto-tracker"
main = "build/worker/shim.mjs"
compatibility_date = "2025-08-16"

[build]
command = "cargo install -q worker-build || true && worker-build --release"
upload.format = "modules"
assets = { directory = "./public", binding = "ASSETS" }

[vars]
DEFAULT_SYMBOLS = "BTC,ETH,ADA,MATIC,AVAX,SOL,LINK,XLM"
APP_ENV = "dev"

[[kv_namespaces]]
binding = "PRICES_KV"
id = "7ff00b77219740a5a51c2abc7e102ee6"              # Put your KV ID here.

[[d1_databases]]
binding = "DB"                                       # This is how Rust will access it: env.d1("DB")
database_name = "crypto_tracker"
database_id = "ff7878c1-c246-45d6-8c8a-cc4f5ab1913c" # Put your D1 ID here.