name = "crypto-tracker"
main = "build/worker/shim.mjs"
compatibility_date = "2025-08-01"
workers_dev = true

[build]
command = "cargo install -q worker-build || true && worker-build --release"
upload.format = "modules"
assets = { directory = "./public", binding = "ASSETS" }

[vars]
DEFAULT_SYMBOLS = "BTC,ETH,ADA,MATIC,AVAX,SOL,LINK,XLM"

[[kv_namespaces]]
binding = "PRICES_KV"
id = ${{ secrets.CF_KV_ID }}

[[d1_databases]]
binding = "DB"
database_name = "crypto_tracker"
database_id = ${{ secrets.CF_D1_ID }}